import re
import unicodedata

# Dicionário de Regras Organizado
RULES = {
    # --- ESSENCIAIS ---
    "Alimentação": [
        "ifood",
        "uber eats",
        "rappi",
        "aiqfome",
        "delivery",
        "mcdonalds",
        "burger king",
        "bk",
        "subway",
        "madero",
        "outback",
        "padaria",
        "panificadora",
        "confeitaria",
        "restaurante",
        "lanchonete",
        "churrascaria",
        "bistro",
        "pizza",
        "supermercado",
        "atacadista",
        "mercado",
        "mercearia",
        "hortifruti",
        "carrefour",
        "pao de acucar",
        "dia%",
        "extra",
        "assai",
        "tenda",
        "sams club",
        "cafe",
        "starbucks",
        "nespresso",
        "coxinha",
        "almoco",
        "jantar",
        "lanche",
        "refeicao",
    ],
    "Transporte": [
        "uber",
        "99",
        "99app",
        "indriver",
        "taxi",
        "cabify",
        "posto",
        "gasolina",
        "etanol",
        "combustivel",
        "abastecimento",
        "ipiranga",
        "shell",
        "br",
        "ale",
        "box",
        "estacionamento",
        "zona azul",
        "park",
        "indigo",
        "sem parar",
        "veloe",
        "conectcar",
        "pedagio",
        "metro",
        "onibus",
        "transporte",
        "bilhete",
        "top",
        "sptrans",
        "riocard",
        "azul linhas",
        "gol",
        "latam",
        "passagem",
    ],
    "Moradia & Contas": [
        "aluguel",
        "quinto andar",
        "imobiliaria",
        "condominio",
        "edificio",
        "residencial",
        "luz",
        "energia",
        "enel",
        "light",
        "cpfl",
        "energisa",
        "cemig",
        "copel",
        "agua",
        "saneamento",
        "sabesp",
        "sanepar",
        "copasa",
        "gas",
        "ultragaz",
        "comgas",
        "internet",
        "claro",
        "vivo",
        "tim",
        "oi",
        "fibra",
        "net",
        "iptu",
        "manutencao",
        "reforma",
        "leroy merlin",
        "telhanorte",
        "recarga",
        "celular"
    ],
    "Saúde": [
        "farmacia",
        "drogasil",
        "drogaria",
        "pague menos",
        "ultrafarma",
        "droga raia",
        "medico",
        "hospital",
        "clinica",
        "laboratorio",
        "exame",
        "consulta",
        "dentista",
        "odont",
        "psicologo",
        "terapia",
        "plano de saude",
        "unimed",
        "amil",
        "sulamerica",
        "bradesco saude",
        "gympass",
        "smartfit",
        "academia",
    ],
    # --- ESTILO DE VIDA ---
    "Lazer & Assinaturas": [
        "netflix",
        "spotify",
        "amazon prime",
        "hbo",
        "disney",
        "globoplay",
        "youtube",
        "apple",
        "google",
        "google play",
        "cinema",
        "cinemark",
        "uci",
        "steam",
        "valve",
        "playstation",
        "psn",
        "xbox",
        "microsoft",
        "nintendo",
        "epic games",
        "riot",
        "nuuvem",
        "blizzard",
        "twitch",
        "bar",
        "pub",
        "cerveja",
        "chopp",
        "adega",
        "ingresso",
        "sympla",
        "eventim",
        "ticket",
        "show",
        "clube",
    ],
    "Educação": [
        "escola",
        "colegio",
        "faculdade",
        "universidade",
        "curso",
        "udemy",
        "alura",
        "coursera",
        "hotmart",
        "kiwify",
        "livraria",
        "saraiva",
        "amazon livros",
        "kindle",
        "papelaria",
    ],
    "Compras": [
        "shopee",
        "mercadolivre",
        "aliexpress",
        "shein",
        "amazon",
        "magalu",
        "magazine luiza",
        "casas bahia",
        "ponto frio",
        "fast shop",
        "roupa",
        "loja",
        "shopping",
        "store",
        "decathlon",
        "centauro",
        "nike",
        "adidas",
        "petz",
        "cobasi",
        "pet",
        "veterinario",
        "Compra no débito",
        "Compra no crédito",
    ],
    # --- FINANCEIRO ---
    "Serviços Financeiros": [
        "pagamento cartao",
        "fatura",
        "card",
        "cartao de credito",
        "emprestimo",
        "financiamento",
        "consorcio",
        "parcela",
        "tarifa",
        "taxa",
        "anuidade",
        "iof",
        "juros",
        "banco",
        "nubank",
        "inter",
        "itau",
        "bradesco",
        "santander",
        "google brasil pagamentos",
        "picpay",
        "pagseguro",
        "mercado pago",
    ],
    "Investimentos": [
        "corretora",
        "nuinvest",
        "xp",
        "btg",
        "rico",
        "clear",
        "orama",
        "aporte",
        "tesouro",
        "cdb",
        "lci",
        "lca",
        "fundos imobiliarios",
        "acoes",
        "b3",
        "cripto",
        "binance",
        "mercadobitcoin",
        "bitcoin",
        "ethereum",
        "wallet",
        "rendimentos",
        "resgate",
        "dividendos",
        "rendimento",
        "fundos",
        "Aplicacao",
    ],
    # --- RECEITAS ---
    "Salário & Renda": [
        "salario",
        "pagamento",
        "holerite",
        "folha",
        "proventos",
        "remuneracao",
        "beneficio",
        "ted recebida",
        "doc recebida",
        "pix recebido",
        "transferencia recebida",
        "deposito",
        "recebido",
        "reembolso",
        "estorno",
        "cashback",
        "Transferência Pix recebida",
    ],
    # --- TRANSFERÊNCIAS (SAÍDAS) ---
    "Transferências": [
        "transferencia enviada",
        "pix enviado",
        "ted enviada",
        "doc enviada",
        "envio pix",
        "Transferência Pix enviada",
        "transferencia pix",
    ],
}


def remove_accents(input_str: str) -> str:
    """
    Normaliza a string removendo acentos.
    Ex: 'Salário' -> 'salario', 'Ônibus' -> 'onibus'
    """
    if not input_str:
        return ""
    # Normaliza unicode (NFD separa o caractere base do acento)
    nfkd_form = unicodedata.normalize("NFKD", input_str)
    # Filtra apenas caracteres não-espaçadores (remove os acentos) e converte para ASCII
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)]).lower()


def predict_category(description: str) -> str:
    """
    Analisa a descrição e retorna a categoria mais provável.
    Retorna 'Outros' se não encontrar nada.
    """
    if not description:
        return "Outros"

    # Limpa a descrição do usuário (remove acentos e põe minúsculo)
    desc_clean = remove_accents(description)

    for categoria, keywords in RULES.items():
        for keyword in keywords:
            # Garante que a keyword da regra também esteja limpa (segurança)
            keyword_clean = remove_accents(keyword)

            # Verifica se a palavra-chave está na descrição limpa
            if keyword_clean in desc_clean:
                return categoria

    return "Outros"