services:
  backend:
    build: ./backend
    container_name: Financias_Backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=sqlite:////app/investimentos.db

  frontend:
    build: ./frontend
    container_name: Financias_Frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  gateway:
      image: caddy:2-alpine
      container_name: Financias_Gateway
      restart: always
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
        - ./tailscale/certs:/tailscale/certs:ro
      depends_on:
        - backend
        - frontend

volumes:
  caddy_data:
  caddy_config:
